name: Koda Auto-Update
on:
  schedule:
    - cron: '*/15 * * * *' # Se ejecuta cada 15 min
  workflow_dispatch: # Permite ejecutarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install gamedig
      - run: node tracker.js
      - name: Commit data
        run: |
          git config --global user.name 'Koda-Bot'
          git config --global user.email 'bot@koda.app'
          git add data.json
          git commit -m "Update server status [skip ci]" || exit 0
          git push
